services:
  node-app:
    container_name: express-node-app-container
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  # postgres:
  #   image: postgres
  #   restart: always
  #   volumes:
  #     - postgres-db:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: example
  redis:
    image: redis

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
volumes:
  mongo-db:
  postgres-db:
