services:
  node-app:
    build:
      context: .
      target: production
    container_name: express-node-app-container
    environment:
      - PORT=4000
      - NODE_ENV=production
    command: npm start
